# Generated by Django 4.1.5 on 2023-01-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250)),
                ("url", models.URLField()),
                ("current_price", models.FloatField(blank=True)),
                ("old_price", models.FloatField(default=0)),
                ("price_difference", models.FloatField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("price_difference", "-created"),
            },
        ),
    ]
